# model name
model: Lasso

# args for GridSearchCV
param_grid:
  alpha:
    - 0.001
    - 0.005
    - 0.01
    - 0.015
    - 0.02
    - 0.03
    - 0.05
    - 0.1
    - 0.3
cv: 5
scoring: neg_mean_absolute_error