# model name
model: RFreg

# args for GridSearchCV
param_grid:
#  n_estimators: [30, 40, 50, 60, 70]
  max_depth: [5, 6, 7, 8, 9, 10, 11, 12, null]
#  max_leaf_nodes: [20, 30, 40, 50]
  max_features: [0.2, 0.3, 0.4, 0.5, "auto"]
  criterion: 
    - mae
cv: 5
scoring: neg_mean_absolute_error